version: 2.1
jobs:
  test-unit:
    docker:
      - image: sineverba/php8xc:1.0.0
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  tests:
    jobs:
      - test-unit
      #- test-unit:
      #    filters:
      #      branches:
      #        only:
      #          - develop
